- name: Install Nginx
  yum:
    name: nginx
    state: installed

- name: Remove html Docs
  file:
    path: /usr/share/nginx/html
    state: absent

- name: Download from github
  include_role:
    name: common
    tasks_from: download-github

- name: start nginx service
  systemd:
    name: nginx
    state: restarted
    enabled: yes