- name: Extract the Downloaded Archive
  unarchive:
    src: https://github.com/roboshop-devops-project/{{COMPONENT}}/archive/main.zip
    dest: /tmp
    remote_src: yes

- name: copy the extracted content
  copy:
    src: /tmp/{{COMPONENT}}-main/static/
    dest: /usr/share/nginx/html
    remote_src: yes
  when: COMPONENT == "frontend"

- name: Copy Files from tmp to app directory
  copy:
    src: /tmp/{{COMPONENT}}-main/
    dest: /home/roboshop/{{COMPONENT}}
    remote_src: yes