- name: Demo of vars on play level
  hosts: all
  vars:
    URL_PLAY: play.example.com
  tasks:
    - name: Print Variable Value
      debug:
        msg: Hello {{ URL_PLAY }}

    - name: Print Variable Again
      debug:
        msg: Bye {{ URL_PLAY }}

- name: Demo on vars in Tasks level
  hosts: all
  tasks:
    - name: print task level variable
      debug:
        msg: Hello {{ URL_TASK1 }}
      vars:
        URL_TASK1: task1.example.com

    - name: print task level variable
      debug:
        msg: hello {{ URL_TASK1 }}

- name: Demo on same var from play and task
  hosts: all
  vars:
    URL: play.example.com
  tasks:
    - name: Print URL
      debug:
        msg: Hello , {{ URL }}
      vars:
        URL: task.example.com
    - name: Print URL
      debug:
        msg: Hello , {{ URL }}