- name: Roboshop Project Setup
  hosts: all
  become: yes
  tasks:
    - name: import frontend role
      import_role:
        name: frontend
      when: APP == "frontend"
      tags: frontend

    - name: import mongodb role
      import_role:
        name: mongodb
      when: APP == "mongodb"
      tags: mongodb

    - name: import catalogue role
      import_role:
        name: catalogue
      when: APP == "catalogue"
      tags: catalogue
