- name: Roboshop Project Setup
  hosts: all
  become: yes
  tasks:
    - name: import frontend role
      import_role:
        name: frontend
      when: APP == "frontend"

    - name: import mongodb role
      import_role:
        name: mongodb
      when: APP == "mongodb"
